-- Smart Infrastructure Platform Database Schema

CREATE TABLE IF NOT EXISTS servers (
id SERIAL PRIMARY KEY,
hostname VARCHAR(255) NOT NULL,
ip_address VARCHAR(100),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS metrics (
id SERIAL PRIMARY KEY,
server_id INTEGER REFERENCES servers(id),
cpu FLOAT NOT NULL,
ram FLOAT NOT NULL,
disk FLOAT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS anomalies (
id SERIAL PRIMARY KEY,
metric_id INTEGER REFERENCES metrics(id),
cpu_status VARCHAR(50) NOT NULL,
ram_status VARCHAR(50) NOT NULL,
disk_status VARCHAR(50) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ml_predictions (
id SERIAL PRIMARY KEY,
metric_id INTEGER REFERENCES metrics(id),
prediction VARCHAR(50) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS automation_logs (
id SERIAL PRIMARY KEY,
metric_id INTEGER NOT NULL,
action VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
